1. Подключает библиотеку

In [2]:
import numpy as np

2. Пример создания массива с помощью np.array

In [10]:
arr = np.array([1, 2, 3, 4, 5]) #создаем массив из списка. Аrray сама базовая операция NumPy для создания массива
print(arr, "\n")

arr = np.zeros((3, 3)) # Массив из нулей (размер 3x3)
print(arr, "\n")

arr_two = np.ones((5, 5)) #массив из едениц (5*5)
print(arr_two, "\n")

arr = np.arange(10) #создает массив c последовательностью чисел от 0 до 9 (как for-ом пройтись)
print(arr, "\n")

[1 2 3 4 5] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[0 1 2 3 4 5 6 7 8 9] 



3. Демонстрация атрибутов

In [13]:
print(arr.shape)#выдает форму массива (длина каждой вложенной секции массивов)
print(arr_two.shape, "\n")

print(arr.dtype, "\n")#тип элементов массива


(10,)
(5, 5) 

int64


4. Пример индексации и срезов

In [24]:
print(arr[1]) #элемент под индексом 1 (тоесть 2й в массиве по порядку)

print(arr_two[1, 3]) #строка с индексом 1 и столбец с индексом 3

idx = np.array([0, 2, 3]) #массив со значениями индексов
print(arr[idx], "\n") #вывод значений по индексам из массива

print(arr[2:8:2]) #со 2 по индексу по 8 элемент не включительно, каждый 2 элемент
arr_two = np.arange(100).reshape(10,10)
print(arr_two[:, 1]) #все строки, 2 столбец (1 по ииндексу)

1
13
[0 2 3] 

[2 4 6]
[ 1 11 21 31 41 51 61 71 81 91]


5. Векторные операции и базовая статика

In [8]:
arr = np.array([20, 30, 40, 50])
arr_two = np.arange(4) # [0 1 2 3]

print(arr + arr_two)   # сложение
print(arr - arr_two)   # вычитание
print(arr * arr_two)   # умножение
print(arr / arr_two)   # деление (деление на 0 дает inf, бесконечность)
print(arr ** arr_two)  # поэлементное возведение в степень
print(arr % arr_two, "\n")   # остаток от деления


print(arr.mean()) #Среднее значение a
print(arr_two.min()) #Минимум в arr_two
print(arr_two.max()) #Максимум в arr_two
print(arr.sum()) #Сумма элементов arr

[20 31 42 53]
[20 29 38 47]
[  0  30  80 150]
[        inf 30.         20.         16.66666667]
[     1     30   1600 125000]
[0 0 0 2] 

35.0
0
3
140


/tmp/ipython-input-4273146867.py:7: RuntimeWarning: divide by zero encountered in divide
  print(arr / arr_two)   # деление (деление на 0 дает inf, бесконечность)
/tmp/ipython-input-4273146867.py:9: RuntimeWarning: divide by zero encountered in remainder
  print(arr % arr_two, "\n")   # остаток от деления
